/*
 Navicat Premium Data Transfer

 Source Server         : localhost_1521_orclpdb
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : GADGETSHOP

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 13/08/2023 22:55:34
*/


-- ----------------------------
-- Table structure for CART
-- ----------------------------
DROP TABLE "GADGETSHOP"."CART";
CREATE TABLE "GADGETSHOP"."CART" (
  "CART_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73392".nextval NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CART
-- ----------------------------

-- ----------------------------
-- Table structure for CATEGORY
-- ----------------------------
DROP TABLE "GADGETSHOP"."CATEGORY";
CREATE TABLE "GADGETSHOP"."CATEGORY" (
  "CATEGORY_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73413".nextval NOT NULL,
  "CATEGORY_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "CHILD_PARENT_CATEGORY_ID" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CATEGORY
-- ----------------------------

-- ----------------------------
-- Table structure for CUSTOMER
-- ----------------------------
DROP TABLE "GADGETSHOP"."CUSTOMER";
CREATE TABLE "GADGETSHOP"."CUSTOMER" (
  "CUSTOMER_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73382".nextval NOT NULL,
  "FIRST_NAME" VARCHAR2(100 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "AREA" VARCHAR2(100 BYTE) VISIBLE,
  "CITY" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "STATE" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "HOUSE" VARCHAR2(100 BYTE) VISIBLE,
  "ROAD" VARCHAR2(100 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(1024 BYTE) VISIBLE NOT NULL,
  "DATE_OF_BIRTH" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CUSTOMER
-- ----------------------------
INSERT INTO "GADGETSHOP"."CUSTOMER" VALUES ('1', 'tamim', 'iqbal', 'BUET', 'Dhaka', 'Dhaka', 'Titumir Hall', NULL, 'abcd@gmail.com', '$2b$10$Jl9EZiQWy0ZSwMqDaYscm.IhHKuDZz4G.bCkW1tq14AXgrd2LyzmO', TO_DATE('2005-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for CUSTOMER_CONTACT_NO
-- ----------------------------
DROP TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO";
CREATE TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO" (
  "CONTACT_NO" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CUSTOMER_CONTACT_NO
-- ----------------------------

-- ----------------------------
-- Table structure for OFFER
-- ----------------------------
DROP TABLE "GADGETSHOP"."OFFER";
CREATE TABLE "GADGETSHOP"."OFFER" (
  "OFFER_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73398".nextval NOT NULL,
  "START_DATE" DATE VISIBLE NOT NULL,
  "END_DATE" DATE VISIBLE NOT NULL,
  "PERCENT_DISCOUNT" NUMBER VISIBLE NOT NULL,
  "MIN_QUANTITY" NUMBER VISIBLE,
  "OFFER_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of OFFER
-- ----------------------------

-- ----------------------------
-- Table structure for ORDERS
-- ----------------------------
DROP TABLE "GADGETSHOP"."ORDERS";
CREATE TABLE "GADGETSHOP"."ORDERS" (
  "ORDER_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73403".nextval NOT NULL,
  "ORDER_DATE" DATE VISIBLE NOT NULL,
  "HOUSE" NUMBER VISIBLE NOT NULL,
  "ROAD" VARCHAR2(100 BYTE) VISIBLE,
  "AREA" VARCHAR2(100 BYTE) VISIBLE,
  "CITY" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "STATE" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "CART_ID" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL,
  "SHIPPING_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORDERS
-- ----------------------------

-- ----------------------------
-- Table structure for ORDER_TRACKING
-- ----------------------------
DROP TABLE "GADGETSHOP"."ORDER_TRACKING";
CREATE TABLE "GADGETSHOP"."ORDER_TRACKING" (
  "TRACKING_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73406".nextval NOT NULL,
  "STATUS" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "ORDER_ID" NUMBER VISIBLE NOT NULL,
  "CART_ID" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORDER_TRACKING
-- ----------------------------

-- ----------------------------
-- Table structure for PAYMENT
-- ----------------------------
DROP TABLE "GADGETSHOP"."PAYMENT";
CREATE TABLE "GADGETSHOP"."PAYMENT" (
  "PAYMENT_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73409".nextval NOT NULL,
  "METHOD" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "ORDER_ID" NUMBER VISIBLE NOT NULL,
  "CART_ID" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PAYMENT
-- ----------------------------

-- ----------------------------
-- Table structure for PRODUCT
-- ----------------------------
DROP TABLE "GADGETSHOP"."PRODUCT";
CREATE TABLE "GADGETSHOP"."PRODUCT" (
  "PRODUCT_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73416".nextval NOT NULL,
  "TITLLE" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "PRICE" NUMBER VISIBLE NOT NULL,
  "STOCK" NUMBER VISIBLE,
  "DESCRIPTION" VARCHAR2(2048 BYTE) VISIBLE,
  "IMAGE" VARCHAR2(1024 BYTE) VISIBLE DEFAULT 'https://www.pexels.com/photo/top-view-photo-gadgets-on-hardwood-floor-3178938/',
  "SUPPLIER_ID" NUMBER VISIBLE NOT NULL,
  "CATEGORY_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRODUCT
-- ----------------------------

-- ----------------------------
-- Table structure for PRODUCT_CART
-- ----------------------------
DROP TABLE "GADGETSHOP"."PRODUCT_CART";
CREATE TABLE "GADGETSHOP"."PRODUCT_CART" (
  "QUANTITY" NUMBER VISIBLE NOT NULL,
  "CART_ID" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL,
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "SUPPLIER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRODUCT_CART
-- ----------------------------

-- ----------------------------
-- Table structure for PRODUCT_FEATURES
-- ----------------------------
DROP TABLE "GADGETSHOP"."PRODUCT_FEATURES";
CREATE TABLE "GADGETSHOP"."PRODUCT_FEATURES" (
  "FEATURES" NUMBER VISIBLE NOT NULL,
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "SUPPLIER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRODUCT_FEATURES
-- ----------------------------

-- ----------------------------
-- Table structure for PRODUCT_OFFER
-- ----------------------------
DROP TABLE "GADGETSHOP"."PRODUCT_OFFER";
CREATE TABLE "GADGETSHOP"."PRODUCT_OFFER" (
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "SUPPLIER_ID" NUMBER VISIBLE NOT NULL,
  "OFFER_ID" NUMBER VISIBLE NOT NULL,
  "START_DATE" DATE VISIBLE NOT NULL,
  "END_DATE" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRODUCT_OFFER
-- ----------------------------

-- ----------------------------
-- Table structure for REVIEWS
-- ----------------------------
DROP TABLE "GADGETSHOP"."REVIEWS";
CREATE TABLE "GADGETSHOP"."REVIEWS" (
  "RATINGS" NUMBER VISIBLE,
  "COMMENTS" VARCHAR2(2048 BYTE) VISIBLE,
  "CUSTOMER_ID" NUMBER VISIBLE NOT NULL,
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "SUPPLIER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of REVIEWS
-- ----------------------------

-- ----------------------------
-- Table structure for SHIPPING_METHOD
-- ----------------------------
DROP TABLE "GADGETSHOP"."SHIPPING_METHOD";
CREATE TABLE "GADGETSHOP"."SHIPPING_METHOD" (
  "SHIPPING_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73395".nextval NOT NULL,
  "SHIPPING_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "CHARGE" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SHIPPING_METHOD
-- ----------------------------

-- ----------------------------
-- Table structure for SUPPLIER
-- ----------------------------
DROP TABLE "GADGETSHOP"."SUPPLIER";
CREATE TABLE "GADGETSHOP"."SUPPLIER" (
  "SUPPLIER_ID" NUMBER VISIBLE DEFAULT "GADGETSHOP"."ISEQ$$_73387".nextval NOT NULL,
  "COMPANY_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "HOUSE" VARCHAR2(100 BYTE) VISIBLE,
  "ROAD" VARCHAR2(100 BYTE) VISIBLE,
  "AREA" VARCHAR2(100 BYTE) VISIBLE,
  "CITY" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "STATE" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "EMAIL" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "WEBSITE" VARCHAR2(1024 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(1024 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SUPPLIER
-- ----------------------------

-- ----------------------------
-- Sequence structure for ISEQ$$_73382
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73382";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73382" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73387
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73387";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73387" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73392
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73392";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73392" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73395
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73395";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73395" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73398
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73398";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73398" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73403
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73403";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73403" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73406
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73406";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73406" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73409
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73409";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73409" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73413
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73413";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73413" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_73416
-- ----------------------------
DROP SEQUENCE "GADGETSHOP"."ISEQ$$_73416";
CREATE SEQUENCE "GADGETSHOP"."ISEQ$$_73416" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CART" ADD CONSTRAINT "SYS_C007758" PRIMARY KEY ("CART_ID", "CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CART" ADD CONSTRAINT "SYS_C007756" CHECK ("CART_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CART" ADD CONSTRAINT "SYS_C007757" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CATEGORY
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CATEGORY" ADD CONSTRAINT "SYS_C007801" PRIMARY KEY ("CATEGORY_ID");

-- ----------------------------
-- Checks structure for table CATEGORY
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CATEGORY" ADD CONSTRAINT "SYS_C007799" CHECK ("CATEGORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CATEGORY" ADD CONSTRAINT "SYS_C007800" CHECK ("CATEGORY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007743" PRIMARY KEY ("CUSTOMER_ID");

-- ----------------------------
-- Uniques structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007744" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007745" UNIQUE ("PASSWORD") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007736" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007737" CHECK ("LAST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007738" CHECK ("CITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007739" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007740" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007741" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER" ADD CONSTRAINT "SYS_C007742" CHECK ("DATE_OF_BIRTH" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CUSTOMER_CONTACT_NO
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO" ADD CONSTRAINT "SYS_C007772" PRIMARY KEY ("CONTACT_NO", "CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table CUSTOMER_CONTACT_NO
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO" ADD CONSTRAINT "SYS_C007770" CHECK ("CONTACT_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO" ADD CONSTRAINT "SYS_C007771" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table OFFER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007769" PRIMARY KEY ("OFFER_ID", "START_DATE", "END_DATE");

-- ----------------------------
-- Checks structure for table OFFER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007764" CHECK ("OFFER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007765" CHECK ("START_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007766" CHECK ("END_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007767" CHECK ("PERCENT_DISCOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."OFFER" ADD CONSTRAINT "SYS_C007768" CHECK ("OFFER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ORDERS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007782" PRIMARY KEY ("ORDER_ID", "CART_ID", "CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table ORDERS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007774" CHECK ("ORDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007775" CHECK ("ORDER_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007776" CHECK ("HOUSE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007777" CHECK ("CITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007778" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007779" CHECK ("CART_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007780" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007781" CHECK ("SHIPPING_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ORDER_TRACKING
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007790" PRIMARY KEY ("TRACKING_ID", "ORDER_ID", "CART_ID", "CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table ORDER_TRACKING
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007785" CHECK ("TRACKING_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007786" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007787" CHECK ("ORDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007788" CHECK ("CART_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007789" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PAYMENT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007797" PRIMARY KEY ("PAYMENT_ID", "ORDER_ID", "CART_ID", "CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table PAYMENT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007792" CHECK ("PAYMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007793" CHECK ("METHOD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007794" CHECK ("ORDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007795" CHECK ("CART_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007796" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRODUCT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007808" PRIMARY KEY ("PRODUCT_ID", "SUPPLIER_ID");

-- ----------------------------
-- Checks structure for table PRODUCT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007803" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007804" CHECK ("TITLLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007805" CHECK ("PRICE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007806" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007807" CHECK ("CATEGORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRODUCT_CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007824" PRIMARY KEY ("CART_ID", "CUSTOMER_ID", "PRODUCT_ID", "SUPPLIER_ID");

-- ----------------------------
-- Checks structure for table PRODUCT_CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007819" CHECK ("QUANTITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007820" CHECK ("CART_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007821" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007822" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007823" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRODUCT_FEATURES
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_FEATURES" ADD CONSTRAINT "SYS_C007836" PRIMARY KEY ("FEATURES", "PRODUCT_ID", "SUPPLIER_ID");

-- ----------------------------
-- Checks structure for table PRODUCT_FEATURES
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_FEATURES" ADD CONSTRAINT "SYS_C007833" CHECK ("FEATURES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_FEATURES" ADD CONSTRAINT "SYS_C007834" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_FEATURES" ADD CONSTRAINT "SYS_C007835" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PRODUCT_OFFER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007816" PRIMARY KEY ("PRODUCT_ID", "SUPPLIER_ID", "OFFER_ID");

-- ----------------------------
-- Checks structure for table PRODUCT_OFFER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007811" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007812" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007813" CHECK ("OFFER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007814" CHECK ("START_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007815" CHECK ("END_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REVIEWS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007830" PRIMARY KEY ("CUSTOMER_ID", "PRODUCT_ID", "SUPPLIER_ID");

-- ----------------------------
-- Checks structure for table REVIEWS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007827" CHECK ("CUSTOMER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007828" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007829" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SHIPPING_METHOD
-- ----------------------------
ALTER TABLE "GADGETSHOP"."SHIPPING_METHOD" ADD CONSTRAINT "SYS_C007763" PRIMARY KEY ("SHIPPING_ID");

-- ----------------------------
-- Checks structure for table SHIPPING_METHOD
-- ----------------------------
ALTER TABLE "GADGETSHOP"."SHIPPING_METHOD" ADD CONSTRAINT "SYS_C007760" CHECK ("SHIPPING_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SHIPPING_METHOD" ADD CONSTRAINT "SYS_C007761" CHECK ("SHIPPING_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SHIPPING_METHOD" ADD CONSTRAINT "SYS_C007762" CHECK ("CHARGE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SUPPLIER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007753" PRIMARY KEY ("SUPPLIER_ID");

-- ----------------------------
-- Uniques structure for table SUPPLIER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007754" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007755" UNIQUE ("PASSWORD") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table SUPPLIER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007746" CHECK ("SUPPLIER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007747" CHECK ("COMPANY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007748" CHECK ("CITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007749" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007750" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007751" CHECK ("WEBSITE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."SUPPLIER" ADD CONSTRAINT "SYS_C007752" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CART" ADD CONSTRAINT "SYS_C007759" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "GADGETSHOP"."CUSTOMER" ("CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CATEGORY
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CATEGORY" ADD CONSTRAINT "SYS_C007802" FOREIGN KEY ("CHILD_PARENT_CATEGORY_ID") REFERENCES "GADGETSHOP"."CATEGORY" ("CATEGORY_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table CUSTOMER_CONTACT_NO
-- ----------------------------
ALTER TABLE "GADGETSHOP"."CUSTOMER_CONTACT_NO" ADD CONSTRAINT "SYS_C007773" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "GADGETSHOP"."CUSTOMER" ("CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ORDERS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007783" FOREIGN KEY ("CART_ID", "CUSTOMER_ID") REFERENCES "GADGETSHOP"."CART" ("CART_ID", "CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."ORDERS" ADD CONSTRAINT "SYS_C007784" FOREIGN KEY ("SHIPPING_ID") REFERENCES "GADGETSHOP"."SHIPPING_METHOD" ("SHIPPING_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ORDER_TRACKING
-- ----------------------------
ALTER TABLE "GADGETSHOP"."ORDER_TRACKING" ADD CONSTRAINT "SYS_C007791" FOREIGN KEY ("ORDER_ID", "CART_ID", "CUSTOMER_ID") REFERENCES "GADGETSHOP"."ORDERS" ("ORDER_ID", "CART_ID", "CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PAYMENT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PAYMENT" ADD CONSTRAINT "SYS_C007798" FOREIGN KEY ("ORDER_ID", "CART_ID", "CUSTOMER_ID") REFERENCES "GADGETSHOP"."ORDERS" ("ORDER_ID", "CART_ID", "CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRODUCT
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007809" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "GADGETSHOP"."SUPPLIER" ("SUPPLIER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT" ADD CONSTRAINT "SYS_C007810" FOREIGN KEY ("CATEGORY_ID") REFERENCES "GADGETSHOP"."CATEGORY" ("CATEGORY_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRODUCT_CART
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007825" FOREIGN KEY ("CART_ID", "CUSTOMER_ID") REFERENCES "GADGETSHOP"."CART" ("CART_ID", "CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_CART" ADD CONSTRAINT "SYS_C007826" FOREIGN KEY ("PRODUCT_ID", "SUPPLIER_ID") REFERENCES "GADGETSHOP"."PRODUCT" ("PRODUCT_ID", "SUPPLIER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRODUCT_FEATURES
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_FEATURES" ADD CONSTRAINT "SYS_C007837" FOREIGN KEY ("PRODUCT_ID", "SUPPLIER_ID") REFERENCES "GADGETSHOP"."PRODUCT" ("PRODUCT_ID", "SUPPLIER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRODUCT_OFFER
-- ----------------------------
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007817" FOREIGN KEY ("PRODUCT_ID", "SUPPLIER_ID") REFERENCES "GADGETSHOP"."PRODUCT" ("PRODUCT_ID", "SUPPLIER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."PRODUCT_OFFER" ADD CONSTRAINT "SYS_C007818" FOREIGN KEY ("OFFER_ID", "START_DATE", "END_DATE") REFERENCES "GADGETSHOP"."OFFER" ("OFFER_ID", "START_DATE", "END_DATE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REVIEWS
-- ----------------------------
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007831" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "GADGETSHOP"."CUSTOMER" ("CUSTOMER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "GADGETSHOP"."REVIEWS" ADD CONSTRAINT "SYS_C007832" FOREIGN KEY ("PRODUCT_ID", "SUPPLIER_ID") REFERENCES "GADGETSHOP"."PRODUCT" ("PRODUCT_ID", "SUPPLIER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
